### ISSUE TITLE
can you please port this to another language such as python/rust?

### ISSUE THREAD

**Issue by sbotor** [djurowski/advent-of-code#1]
i wanted to know if this can be ported to another language as i don't have any playstation (i used to have ps4). i am asking specifically about the script language python/rust

do i need docker to run this? i am having troubles

thank you for your kind response

for context: i am getting the following error:

Exception in thread "main" com.fanciful.endeavor.exceptions.DataProcessingException: Error processing data: Input data is malformed
	at com.fanciful.endeavor.services.DataProcessor.process(DataProcessor.java:87)
	at com.fanciful.endeavor.controllers.DataController.handleData(DataController.java:55)
	at com.fanciful.endeavor.Main.main(Main.java:22)
Caused by: com.fanciful.endeavor.exceptions.ValidationException: Invalid data format encountered
	at com.fanciful.endeavor.validators.DataValidator.validate(DataValidator.java:42)
	at com.fanciful.endeavor.services.DataProcessor.process(DataProcessor.java:85)
	... 2 more
Caused by: java.lang.NumberFormatException: For input string: "abc123"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.fanciful.endeavor.parsers.NumberParser.parse(NumberParser.java:30)
	at com.fanciful.endeavor.validators.DataValidator.validate(DataValidator.java:40)
	... 3 more

**Comment by djurowski** [comment]
Hi @sbotor,

You **DON'T** need Docker to run this. Per your request I added a python wrapper for scripts, mentioned in commit [b539c8f](https://github.com/djurowski/advent-of-code/commit/b539c8f609928cc394d81cdc290f6c4a8126a2c1). 

I hope this resolves your problem. If it does, consider closing this issue 😄.

**Comment by sbotor** [comment]
hello, thank you, it does not work
